services:
  db:
    image: mongodb/mongodb-community-server:latest
  web:
    # image: node:21
    build: ./CNIT484Group1
    ports:
      - "8000:3000"
      # - "443:443"
    depends_on:
      - db
